[project]
name = "helloworld"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sadankumar", email = "sadan.2507@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "black>=26.5.1",
    "isort>=9.0.1",
    "langchain>=1.4.0",
    "langchain-ollama>=1.1.0",
    "langchain-openai>=1.6.2",
    "python-dotenv>=1.2.3",
]

[project.scripts]
helloworld = "helloworld:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
